cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build

before_script:
  - npm --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc install

docker_image:
  stage: build
  script:
    - set -eo pipefail
    - npm run build:${ENV}
    - cp -r dist docker/dist
    - cd docker && docker build -t harbor.ziroom.com/${TAG}:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID .
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} harbor.ziroom.com
    - docker push harbor.ziroom.com/${TAG}:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
  only:
    - api
    - trigger
